### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by agurzau** [x89/Shreddit#109]
im getting this error when i run Shreddit command after setting everything up.

Traceback (most recent call last):
  File "E:\Python\Scripts\shreddit-script.py", line 11, in <module>
    load_entry_point('shreddit==6.0.7', 'console_scripts', 'shreddit')()
  File "e:\python\lib\site-packages\shreddit\app.py", line 44, in main
    shredder = Shredder(default_config, args.user)
  File "e:\python\lib\site-packages\shreddit\shredder.py", line 28, in __init__
    self._connect()
  File "e:\python\lib\site-packages\shreddit\shredder.py", line 80, in _connect
    self._r = praw.Reddit(self._user, check_for_updates=False, user_agent="python:shreddit:v6.0.4")
  File "e:\python\lib\site-packages\praw\reddit.py", line 129, in __init__
    self.config = Config(config_section, **config_settings)
  File "e:\python\lib\site-packages\praw\config.py", line 63, in __init__
    self._load_config()
  File "e:\python\lib\site-packages\praw\config.py", line 49, in _load_config
    config.read(locations)
  File "e:\python\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "e:\python\lib\configparser.py", line 1111, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: 'praw.ini'
        [line 12]: "'mypassword'"

**Comment by agurzau** [comment]
screwed up the formatting of my praw.ini file.
