### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by batmancurtis** [x89/Shreddit#110]
after doing shreddit -g the praw.ini file is not opening please help

  Timothys-MacBook-Air:~ Curtis$ shreddit
Traceback (most recent call last):
  File "/usr/local/bin/shreddit", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/shreddit/app.py", line 44, in main
    shredder = Shredder(default_config, args.user)
  File "/Library/Python/2.7/site-packages/shreddit/shredder.py", line 28, in __init__
    self._connect()
  File "/Library/Python/2.7/site-packages/shreddit/shredder.py", line 80, in _connect
    self._r = praw.Reddit(self._user, check_for_updates=False, user_agent="python:shreddit:v6.0.4")
  File "/Library/Python/2.7/site-packages/praw/reddit.py", line 150, in __init__
    raise ClientException(required_message.format(attribute))
praw.exceptions.ClientException: Required configuration setting 'client_id' missing. 
This setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable.
Timothys-MacBook-Air:~ Curtis$ praw.ini
-bash: praw.ini: command not found
Timothys-MacBook-Air:~ Curtis$ shreddit -g
Timothys-MacBook-Air:~ Curtis$ shreddit -g

**Comment by Apple-Lion** [comment]
Follow the instructions mate. 

https://pypi.python.org/pypi/shreddit/6.0.6

You need to edit your praw.ini and add not only your account details but also the hidden 14 char token and secret string created in the instructions on the Reddit site. 

Try that and come back and follow up.
