### ISSUE TITLE
Errors Installing From Requirements.txt

### ISSUE THREAD

**Issue by ghost** [x89/Shreddit#115]
I was just following the directions. Everything goes fine up until `pip install -r requirements.txt`, upon which I'm hit with a wall of red text.

Replacing my OS username with "xxxx" because I don't want it displayed here.

```
Invalid requirement: '<<<<<<< HEAD'
Traceback (most recent call last):
  File "c:\users\xxxx\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\packaging\requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "c:\users\xxxx\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\pyparsing.py", line 1617, in parseString
    raise exc
  File "c:\users\xxxx\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "c:\users\xxxx\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\xxxx\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "c:\users\xxxx\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\xxxx\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "c:\users\xxxx\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\xxxx\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "c:\users\xxxx\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\xxxx\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\pyparsing.py", line 2670, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\xxxx\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 82, in __init__
    req = Requirement(req)
  File "c:\users\xxxx\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\packaging\requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'<<<<<<< '"
```

What do?

**Comment by DennisVonDerBey** [comment]
Edit the file so that it looks like this.

https://github.com/x89/Shreddit/pull/103/commits/891fbc6a677545c2636265270436ccbb971d17a6
