### ISSUE TITLE
Can not get script to work, unsure why, probably user error though.

### ISSUE THREAD

**Issue by enaidyl** [x89/Shreddit#117]
I've never run a python script before, so I have no idea what I'm doing wrong. I think I set up the praw file right, but I really have not idea. This is the output I'm getting when I try to run the script:

``Traceback (most recent call last):
  File "C:\Users\******\AppData\Local\Programs\Python\Python36\Scripts\shreddit-script.py", line 11, in <module>
    load_entry_point('shreddit==6.0.7', 'console_scripts', 'shreddit')()
  File "c:\users\******\appdata\local\programs\python\python36\lib\site-packages\shreddit\app.py", line 44, in main
    shredder = Shredder(default_config, args.user)
  File "c:\users\******\appdata\local\programs\python\python36\lib\site-packages\shreddit\shredder.py", line 28, in __init__
    self._connect()
  File "c:\users\******\appdata\local\programs\python\python36\lib\site-packages\shreddit\shredder.py", line 80, in _connect
    self._r = praw.Reddit(self._user, check_for_updates=False, user_agent="python:shreddit:v6.0.4")
  File "c:\users\******\appdata\local\programs\python\python36\lib\site-packages\praw\reddit.py", line 129, in __init__
    self.config = Config(config_section, **config_settings)
  File "c:\users\******\appdata\local\programs\python\python36\lib\site-packages\praw\config.py", line 63, in __init__
    self._load_config()
  File "c:\users\l******\appdata\local\programs\python\python36\lib\site-packages\praw\config.py", line 49, in _load_config
    config.read(locations)
  File "c:\users\******\appdata\local\programs\python\python36\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "c:\users\******\appdata\local\programs\python\python36\lib\configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'praw.ini', line: 3
'which set to use.\n'``

I honestly have no idea what any of this means. Usually I can work this kind of stuff out, but I'm stuck.

**Comment by SpiritQuaddicted** [comment]
> I think I set up the praw file right

You didn't. Post the content (with the actual values replaced, do not post your personal details!).
