### ISSUE TITLE
Suddenly stopped working, OAuthException

### ISSUE THREAD

**Issue by Tjololo12** [x89/Shreddit#139]
Has been working fine until recently, when I'm getting a new error. Looks like an auth error, but none of my information has changed (as verified on the app page in my reddit settings)

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/shreddit/shredder.py", line 81, in _connect
    self._logger.info("Logged in as {user}.".format(user=self._r.user.me()))
  File "/usr/lib/python3.4/site-packages/praw/models/user.py", line 60, in me
    user_data = self._reddit.get(API_PATH['me'])
  File "/usr/lib/python3.4/site-packages/praw/reddit.py", line 367, in get
    data = self.request('GET', path, params=params)
  File "/usr/lib/python3.4/site-packages/praw/reddit.py", line 472, in request
    params=params)
  File "/usr/lib/python3.4/site-packages/prawcore/sessions.py", line 175, in request
    params=params, url=url)
  File "/usr/lib/python3.4/site-packages/prawcore/sessions.py", line 109, in _request_with_retries
    data, files, json, method, params, retries, url)
  File "/usr/lib/python3.4/site-packages/prawcore/sessions.py", line 94, in _make_request
    params=params)
  File "/usr/lib/python3.4/site-packages/prawcore/rate_limit.py", line 32, in call
    kwargs['headers'] = set_header_callback()
  File "/usr/lib/python3.4/site-packages/prawcore/sessions.py", line 135, in _set_header_callback
    self._authorizer.refresh()
  File "/usr/lib/python3.4/site-packages/prawcore/auth.py", line 328, in refresh
    password=self._password)
  File "/usr/lib/python3.4/site-packages/prawcore/auth.py", line 142, in _request_token
    payload.get('error_description'))
prawcore.exceptions.OAuthException: invalid_grant error processing request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/shreddit", line 9, in <module>
    load_entry_point('shreddit==6.0.7', 'console_scripts', 'shreddit')()
  File "/usr/lib/python3.4/site-packages/shreddit/app.py", line 44, in main
    shredder = Shredder(default_config, args.user)
  File "/usr/lib/python3.4/site-packages/shreddit/shredder.py", line 28, in __init__
    self._connect()
  File "/usr/lib/python3.4/site-packages/shreddit/shredder.py", line 85, in _connect
    raise ShredditError("Bad username or password")
shreddit.util.ShredditError: 'Bad username or password'

**Comment by Tjololo12** [comment]
Ah, it appears the problem is with 2FA, which is a known problem.
