### ISSUE TITLE
The program cannot be installed

### ISSUE THREAD

**Issue by 35609902357** [x89/Shreddit#147]
If I install the program using `sudo pip install -U shreddit` I get an error saying
`praw requires Python '>=3.4' but the running Python is 2.7.16`.
`python3` version is `3.7.3`
`python` version is `2.7.16`
If I install it using `sudo pip3 install -U shreddit` the installer succeeds, but when I launch it I get this error

    shreddit -u user
    INFO:shreddit:Logged in as user.
    Traceback (most recent call last):
      File "/usr/local/bin/shreddit", line 10, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.7/dist-packages/shreddit/app.py", line 44, in main
        shredder = Shredder(default_config, args.user)
      File "/usr/local/lib/python3.7/dist-packages/shreddit/shredder.py", line 33, in __init__
        self._recent_cutoff = arrow.now().replace(hours=-self._hours)
      File "/usr/local/lib/python3.7/dist-packages/arrow/arrow.py", line 603, in replace
        raise AttributeError('unknown attribute: "{}"'.format(key))
    AttributeError: unknown attribute: "hours"

**Comment by EthanZeigler** [comment]
See #146
