### ISSUE TITLE
Read-Only File system?

### ISSUE THREAD

**Issue by liamvgallagher** [x89/Shreddit#157]
I have never encountered this error, how should I fix it?

`Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/shreddit", line 11, in <module>
    load_entry_point('shreddit==6.0.7', 'console_scripts', 'shreddit')()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/shreddit-6.0.7-py3.8.egg/shreddit/app.py", line 53, in main
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/shreddit-6.0.7-py3.8.egg/shreddit/shredder.py", line 37, in __init__
  File "/data/data/com.termux/files/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/tmp'`

**Comment by pythonInRelay** [comment]
Clone my repo and run that instead, it has a numerous amount of improvements and updates.
