### ISSUE TITLE
Can't quite figure it out

### ISSUE THREAD

**Issue by ghost** [x89/Shreddit#162]
-

**Comment by pythonInRelay** [comment]
Hi,

I see you're new here but Github isn't generally a place for asking for troubleshooting help, but reporting issues or unexpected problems with content shared here.

Please follow the instructions carefully.

You seem to be running Windows. So download the latest Python 2 for Windows and install it and make sure to add Python to PATH during the installation.

The instructions are very clear and even someone with no programming knowledge can easily set this up in just a few minutes.

In short, you install Python, set up an app link on Reddit, input the secret and app ID to the shreddit program, including your reddit username and password, set what content you want mass deleted and what you want kept. Then run the program. You literally only need to run one command:

`shreddit`

That's it. I cannot make it more simple than this due to how reddit works. The script itself (my fork at least) works 100%. I used it just the other day. Other alternatives would be to stop using reddit altogether (because its a dumpsterfire) or delete your entire account.

**Comment by hugemassivethrowaway** [comment]
I did some other things and ended up getting it to login. It ended with an error though

INFO:shreddit:Logged in as ----.
Traceback (most recent call last):
  File "C:\Users\----\AppData\Local\Programs\Python\Python39\Scripts\shreddit-script.py", line 33, in <module>
    sys.exit(load_entry_point('shreddit==6.0.7', 'console_scripts', 'shreddit')())
  File "c:\users\-----\appdata\local\programs\python\python39\lib\site-packages\shreddit\app.py", line 44, in main
    shredder = Shredder(default_config, args.user)
  File "c:\users\-------\appdata\local\programs\python\python39\lib\site-packages\shreddit\shredder.py", line 33, in __init__
    self._recent_cutoff = arrow.now().replace(hours=-self._hours)
  File "c:\users\------\appdata\local\programs\python\python39\lib\site-packages\arrow\arrow.py", line 807, in replace
    raise AttributeError('unknown attribute: "{}"'.format(key))
AttributeError: unknown attribute: "hours"

I know this is a stupid question, but does Python 2 count as Python 3.9.1? That's what I'm using.

Sorry again, no need to be so condescending.

**Comment by pythonInRelay** [comment]
1. https://youtu.be/CKcqniGu3tA
2. https://youtu.be/nT8KGYVurIU
3. https://youtu.be/aJ_Vfqmf1ow
4. https://youtu.be/c_qNC1lL4qA
5. https://youtu.be/TXEyNQDIrwc

**Comment by hugemassivethrowaway** [comment]
Thank you, sorry about that. I guess I didn't have git installed so now I do. When I try to do anything with apt, it says the command is not found. Am I missing something?

Thanks again

**Comment by pythonInRelay** [comment]
Hi,

At this stage I have no idea what you are having problems with. I really recommend you just clone my fork and follow the instructions. I cannot make it any clearer than that.

**Comment by stickerx** [comment]
Hi

can you make a simple tutorial video 1-2miut

**Comment by pythonInRelay** [comment]
> 
> 
> Hi
> 
> can you make a simple tutorial video 1-2miut

It's quite an unnecessary thing to do if you follow the instructions.
However if you really cannot make sense of it. Then sure. [If you pay me.](https://paypal.me/djbp)

**Comment by pythonInRelay** [comment]
No.
