### ISSUE TITLE
Crashing after a while

### ISSUE THREAD

**Issue by noflag** [x89/Shreddit#39]
`Traceback (most recent call last):
  File "shreddit.py", line 198, in <module>
    count = remove_things(things)
  File "shreddit.py", line 187, in remove_things
    thing.edit(replacement_text)
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 348, in wrapped
    return function(cls, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/objects.py", line 308, in edit
    response = self.reddit_session.request_json(url, data=data)
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 173, in wrapped
    return_value = function(reddit_session, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 579, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 424, in _request
    _raise_response_exceptions(response)
  File "/usr/local/lib/python2.7/dist-packages/praw/internal.py", line 196, in _raise_response_exceptions
    raise Forbidden(_raw=response)
praw.errors.Forbidden`

**Comment by noflag** [comment]
I think it's just running out of things to delete

**Comment by x89** [comment]
I'll look into this in the morning, best guesses are that password based
login had been deprecated, you've hit some rate limit or something went
wrong with the OAuth permissions.

**Comment by noflag** [comment]
it seems to work now

**Comment by x89** [comment]
I'll close the issue then, let me know.
