### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lunchables** [x89/Shreddit#43]
(Shreddit)[root@dev01 Shreddit]# ./run.sh 
Requirement already up-to-date: praw in ./lib/python2.7/site-packages
Requirement already up-to-date: update-checker>=0.11 in ./lib/python2.7/site-packages (from praw)
Requirement already up-to-date: requests>=2.3.0 in ./lib/python2.7/site-packages (from praw)
Requirement already up-to-date: decorator>=3.4.2 in ./lib/python2.7/site-packages (from praw)
Requirement already up-to-date: six>=1.4 in ./lib/python2.7/site-packages (from praw)
/root/Shreddit/lib/python2.7/site-packages/praw/decorators.py:74: DeprecationWarning: reddit intends to disable password-based authentication of API clients sometime in the near future. As a result this method will be removed in a future major version of PRAW.

For more information please see:

* Original reddit deprecation notice: https://www.reddit.com/comments/2ujhkr/

* Updated delayed deprecation notice: https://www.reddit.com/comments/37e2mv/

Pass ``disable_warning=True`` to ``login`` to disable this warning.
  warn(msg, DeprecationWarning)
Traceback (most recent call last):
  File "./shreddit.py", line 95, in <module>
    login(user=_user, password=_pass)
  File "./shreddit.py", line 84, in login
    r.login(_user, _pass)
  File "<decorator-gen-49>", line 2, in login
  File "/root/Shreddit/lib/python2.7/site-packages/praw/decorators.py", line 75, in wrap
    return function(*args, **kwargs)
  File "/root/Shreddit/lib/python2.7/site-packages/praw/__init__.py", line 1418, in login
    self.request_json(self.config['login'], data=data)
  File "<decorator-gen-8>", line 2, in request_json
  File "/root/Shreddit/lib/python2.7/site-packages/praw/decorators.py", line 113, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/root/Shreddit/lib/python2.7/site-packages/praw/__init__.py", line 612, in request_json
    retry_on_error=retry_on_error)
  File "/root/Shreddit/lib/python2.7/site-packages/praw/__init__.py", line 444, in _request
    response = handle_redirect()
  File "/root/Shreddit/lib/python2.7/site-packages/praw/__init__.py", line 425, in handle_redirect
    verify=self.http.validate_certs, **kwargs)
  File "/root/Shreddit/lib/python2.7/site-packages/praw/handlers.py", line 148, in wrapped
    result = function(cls, **kwargs)
  File "/root/Shreddit/lib/python2.7/site-packages/praw/handlers.py", line 57, in wrapped
    return function(cls, **kwargs)
  File "/root/Shreddit/lib/python2.7/site-packages/praw/handlers.py", line 103, in request
    allow_redirects=False, verify=verify)
  File "/root/Shreddit/lib/python2.7/site-packages/requests/sessions.py", line 579, in send
    r = adapter.send(request, **kwargs)
  File "/root/Shreddit/lib/python2.7/site-packages/requests/adapters.py", line 369, in send
    timeout=timeout
  File "/root/Shreddit/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/root/Shreddit/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 805, in send
    self.sock.sendall(data)
  File "/root/Shreddit/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 216, in sendall
    data = memoryview(data)
TypeError: cannot make memory view because object does not have the buffer interface

**Comment by x89** [comment]
Is the error reproducible? As in it happens every time you try to run it?

I know Shreddit works with Python 2.7 but is there any chance you could perhaps make a Python 3 virtualenv and test from there?

**Comment by lunchables** [comment]
Yeah, reproducible.  I run: source ./bin/activate and get the (Shreddit) prompt then ./run and get the same thing.  That was on centos 7.  I'll see if I can install the SCL for python 3 and try again.


I tried from a fedora machine (also 2.7) and got this:
Traceback (most recent call last):
  File "./shreddit.py", line 71, in <module>
    r = praw.Reddit(user_agent="shreddit/4.0")
  File "/home/jon/Shreddit/lib/python2.7/site-packages/praw/__init__.py", line 1207, in __init__
    super(AuthenticatedReddit, self).__init__(*args, **kwargs)
  File "/home/jon/Shreddit/lib/python2.7/site-packages/praw/__init__.py", line 642, in __init__
    super(OAuth2Reddit, self).__init__(*args, **kwargs)
  File "/home/jon/Shreddit/lib/python2.7/site-packages/praw/__init__.py", line 763, in __init__
    super(UnauthenticatedReddit, self).__init__(*args, **kwargs)
  File "/home/jon/Shreddit/lib/python2.7/site-packages/praw/__init__.py", line 343, in __init__
    self.http.headers['User-Agent'] = self.config.ua_string(user_agent)
  File "/home/jon/Shreddit/lib/python2.7/site-packages/praw/__init__.py", line 208, in ua_string
    info = platform.platform(True).encode('ascii', 'ignore')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 56: ordinal not in range(128)

**Comment by x89** [comment]
What happens when you open up `python` and enter:

`import platform
platform.platform(True)`

Whatever that returns is throwing a fit within praw's __init__.py.
Any luck with Python 3? It has less issues with Unicode (usually).

**Comment by lunchables** [comment]
>>> import platform
>>> platform.platform(True)
'Linux-3.10.0-229.11.1.el7.x86_64-x86_64-with-centos-7.1.1503-Core'

Still messing around trying to get python3 setup from SCL.

**Comment by x89** [comment]
You could try editing shreddit.py:71 and changing the user_agent to
something else, "donkey" or something… It's down that trace that things are
going wrong there.
I doubt that'll work but it could be worth a shot.

I don't see anything in that platform.platform that couldn't be handled by
.encode('ascii', 'ignore').

**Comment by lunchables** [comment]
Apologies - I updated my last reply.  I'm confusing this by running it in two places. I'm now getting the same buffer error on both platforms.  The fedora machine was returning a very bizarre platform.

**Comment by lunchables** [comment]
Running python3 with virtualenv and it ran successfully (yay!).  So this problem is specific to 2.7.  Thanks for your help!

**Comment by x89** [comment]
I'm glad it's working :+1:
