### ISSUE TITLE
Should ignore clear_vote option for archived submissions

### ISSUE THREAD

**Issue by cefarix** [x89/Shreddit#71]
When trying to remove archived submissions and the clear_vote option is True, shreddit will error out with a cryptic error message. Shreddit should either detect this error and inform the user or ignore the clear_vote option and continue deleting.

**Comment by x89** [comment]
Good point, I've never had an account with > 6 month old content to test clear_vote on.

Perchance would you have the stack trace / error that it outputs?

**Comment by cefarix** [comment]
This was run on WIndows 10, 64-bit Python 3.4. Stack trace:

```
Traceback (most recent call last):
  File "D:\Python3\lib\site-packages\praw\decorators.py", line 124, in raise_api_exceptions
    return_value = {'errors': [(data['reason'],
KeyError: 'reason'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python3\Scripts\shreddit-script.py", line 9, in <module>
    load_entry_point('shreddit==2.0.0', 'console_scripts', 'shreddit')()
  File "D:\Python3\lib\site-packages\shreddit\app.py", line 32, in main
    shredder.shred()
  File "D:\Python3\lib\site-packages\shreddit\shredder.py", line 53, in shred
    deleted = self._remove_things(self._get_things())
  File "D:\Python3\lib\site-packages\shreddit\shredder.py", line 158, in _remove_things
    self._remove(item)
  File "D:\Python3\lib\site-packages\shreddit\shredder.py", line 134, in _remove
    item.clear_vote()
  File "D:\Python3\lib\site-packages\praw\objects.py", line 572, in clear_vote
    return self.vote()
  File "<decorator-gen-177>", line 2, in vote
  File "D:\Python3\lib\site-packages\praw\decorators.py", line 277, in wrap
    return function(*args, **kwargs)
  File "D:\Python3\lib\site-packages\praw\objects.py", line 627, in vote
    return self.reddit_session.request_json(url, data=data)
  File "<decorator-gen-8>", line 2, in request_json
  File "D:\Python3\lib\site-packages\praw\decorators.py", line 127, in raise_api_exceptions
    raise exc
  File "D:\Python3\lib\site-packages\praw\decorators.py", line 117, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "D:\Python3\lib\site-packages\praw\__init__.py", line 620, in request_json
    retry_on_error=retry_on_error)
  File "D:\Python3\lib\site-packages\praw\__init__.py", line 452, in _request
    _raise_response_exceptions(response)
  File "D:\Python3\lib\site-packages\praw\internal.py", line 246, in _raise_response_exceptions
    raise HTTPException(_raw=exc.response)
praw.errors.HTTPException: HTTP error
```

**Comment by x89** [comment]
Thank you, I shall take a look into it.

**Comment by x89** [comment]
@cefarix could you potentially try using this branch https://github.com/x89/Shreddit/tree/71-clear_vote_archived_submissions ?

**Comment by cefarix** [comment]
I don't have an account to test it on anymore.

**Comment by x89** [comment]
I'll assume the problem fixed then, I think the above code should work — if not this bug can be re-opened.
