### ISSUE TITLE
Crash: 'Comment' has no attribute 'json_dict' 

### ISSUE THREAD

**Issue by e1hd983** [x89/Shreddit#83]
I tried running a trial run, with latest Shreddit checkout, and saving all comments older than 24 hours. However, it crashes, and gives me the following output:

Traceback (most recent call last):
  File "shreddit/app.py", line 49, in <module>
    main()
  File "shreddit/app.py", line 45, in main
    shredder.shred()
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/shreddit/shredder.py", line 67, in shred
    deleted = self._remove_things(self._build_iterator())
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/shreddit/shredder.py", line 161, in _remove_things
    self._remove(item)
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/shreddit/shredder.py", line 126, in _remove
    self._save_item(item)
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/shreddit/shredder.py", line 104, in _save_item
    json.dump(item.json_dict, fh)
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/praw/models/reddit/base.py", line 34, in \_\_getattr\_\_
    .format(self.\_\_class\_\_.\_\_name\_\_, attribute))
AttributeError: 'Comment' object has no attribute 'json_dict'

I dumped "item"'s \_\_dict\_\_ property to the console, and didn't see any property with the name 'json_dict'.

**Comment by e1hd983** [comment]
Here's a question: is json_dict just supposed to be a json string version of the item's __dict__ dictionary? If I find a way to convert the __dict__ to a json string on that line, would that be an effective fix?

**Comment by scott-hand** [comment]
Oh boy, looks like a PRAW 3 -> 4 regression. PRAW3 stored lazy loaded JSON info for objects in their `.json_dict` attribute to make it really simple to store data. Looks like that might not be the case any more. Thanks for bringing this up.

**Comment by e1hd983** [comment]
Gladly. Thanks for all your work on this project. It's very helpful, and very easy to use.

**Comment by scott-hand** [comment]
@e1hd983 The fixed version has been pushed and should be live on PyPI. Let me know if this resolved it for you.

**Comment by e1hd983** [comment]
Looks like it's working now. Thanks!

Also, I may have forgotten to run setup.py before. So I might have been using old versions of some of the software. Hope I didn't mislead you regarding the bug at all.

**Comment by scott-hand** [comment]
Don't worry, I was able to reproduce the bug just fine. Thanks again, I'll go ahead and close.
