### ISSUE TITLE
HTTPException when trying to remove an upvote from an archived post

### ISSUE THREAD

**Issue by e1hd983** [x89/Shreddit#86]
Hello again, and thank you for all your help.

Traceback (most recent call last):
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/shreddit-6.0.4-py3.5.egg/shreddit/shredder.py", line 131, in _remove
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/praw/models/reddit/mixins/votable.py", line 22, in clear_vote
    self._vote(direction=0)
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/praw/models/reddit/mixins/votable.py", line 10, in _vote
    'id': self.fullname})
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/praw/reddit.py", line 350, in post
    params=params)
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/praw/reddit.py", line 391, in request
    params=params)
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/prawcore/sessions.py", line 124, in request
    params=params,  url=url)
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/prawcore/sessions.py", line 75, in _request_with_retries
raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.BadRequest: received 400 HTTP response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myusername/anaconda/envs/shreddit2/bin/shreddit", line 11, in <module>
    load_entry_point('shreddit==6.0.4', 'console_scripts', 'shreddit')()
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/shreddit-6.0.4-py3.5.egg/shreddit/app.py", line 45, in main
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/shreddit-6.0.4-py3.5.egg/shreddit/shredder.py", line 68, in shred
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/shreddit-6.0.4-py3.5.egg/shreddit/shredder.py", line 166, in _remove_things
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/shreddit-6.0.4-py3.5.egg/shreddit/shredder.py", line 132, in _remove
NameError: name 'HTTPException' is not defined

**Comment by e1hd983** [comment]
I'm just guessing... but could this be happening when attempting to remove an upvote from a comment when a previous run already removed the upvote? So we would just need to catch a status 400 HTTP response in clear_vote?

**Comment by e1hd983** [comment]
Oh, no, we are trying to catch the HTTPException, but it says the "name HTTPException is not defined."

**Comment by e1hd983** [comment]
I'm tempted to just "catch:" everything as a temporary fix, but I'm concerned, because I guess it might not clear votes if I do that?

**Comment by e1hd983** [comment]
Dang, I just found the comment in question, and tried to remove my upvote. But the comment is over 6 months old. So Reddit popped up the "this post is archived, you can't comment or post." I think it must be because the comment is too old.

**Comment by scott-hand** [comment]
Good catch! Surprised PRAW doesn't handle this more gracefully but I'll see if I can add something to handle it.

**Comment by scott-hand** [comment]
I see, I didn't catch that the exception itself had changed. Just pushed a fix.

**Comment by e1hd983** [comment]
This fixed it! Thanks.

Slightly off topic: it turns out it was a post, not a comment. There was a comment on the same post that is also 6 months old. However, this 6 month old comment doesn't show up in my comment history, and Shreddit didn't detect it for deletion. Is there some reason that causes a comment not to show up in my account history? It appears to be my first comment for the account in question.

**Comment by e1hd983** [comment]
It looks like if I sort by "top" instead of "new" a bunch of comments appear that I was trying to delete. So Reddit is hiding some of my comments depending on how I sort? That is a bummer, if true. Is there any way to know that I'm actually deleting all of my comments, if some are being hidden based on the sort?

**Comment by scott-hand** [comment]
That's odd. It could be the Reddit API (which I'm not a fan of) or PRAW (which I hated in v3 but might be ok in v4?)

It's worth checking out for yourself though. I'd help but the worst part of PRAW weirdness is that it's basically impossible to replicate without an account with existing comments/submissions.

```python
r = praw.Reddit(<connection options>)
r.user.me().comments # play around with this
```
