### ISSUE TITLE
Bad OAuth credentials

### ISSUE THREAD

**Issue by roydbtR** [x89/Shreddit#96]
I have a praw.ini and when I do `shreddit` it says:
`Traceback (most recent call last):
  File "C:\Python27\Scripts\shreddit-script.py", line 9, in <module>
    load_entry_point('shreddit==6.0.7', 'console_scripts', 'shreddit')()
  File "build\bdist.win32\egg\shreddit\app.py", line 53, in main
  File "build\bdist.win32\egg\shreddit\shredder.py", line 28, in __init__
  File "build\bdist.win32\egg\shreddit\shredder.py", line 83, in _connect
shreddit.util.ShredditError: 'Bad OAuth credentials'`

**Comment by ardeaf** [comment]
Are you sure you copied the right client_id and client_secret?

**Comment by x89** [comment]
Closed similar to #95 due to inactivity.

I'd echo what @ardeaf (and say thanks for responding) - it's going to be an issue with authentication, you need the 4 bits of information, client id and secret, username and password.
