### ISSUE TITLE
Bad username or password?

### ISSUE THREAD

**Issue by Huygenz** [x89/Shreddit#99]
I have a praw.ini filled with all 4 credentials.

When trying to run shreddit I get this:

`Traceback (most recent call last):
  File "/usr/local/bin/shreddit", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/shreddit/app.py", line 44, in main
    shredder = Shredder(default_config, args.user)
  File "/usr/local/lib/python2.7/dist-packages/shreddit/shredder.py", line 28, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/shreddit/shredder.py", line 85, in _connect
    raise ShredditError("Bad username or password")
shreddit.util.ShredditError: 'Bad username or password'`

That's got to be a bug, as when I copy and paste the given username and password from praw.ini into reddit-login on the website it works without a problem.

**Comment by x89** [comment]
Do you mean when you try to log in usually using the front page / login page?

And do you have the username and password variables filled out (as well as
the other keys you should have from "making your own app"?).

**Comment by Huygenz** [comment]
Thanks for responding!

Yes, when testing the same user/pass-combo on reddit frontpage/loginpage it works just fine, so theres 100% no typo on my side in praw.ini

Yes. All four credentials in praw.ini are filled in. Including these two I got from "making your own app".

**Comment by a-SynKronus** [comment]
I believe you might have picked "web app" instead of "script" when choosing your application type.

**Comment by kgillibrand** [comment]
I had this happen because my account had 2 factor authentication enabled, the soloution was to disable it and then re-enable it when I was done with the script.
Reddit didn't support 2FA at the time this issue was created but figured I'd mention it for anyone else.

**Comment by mozilla2012** [comment]
Me too; I just enabled 2FA and it stopped working. Looks like they aren't compatible.

**Comment by Behinder** [comment]
This is definitely not related to 2FA. I have this on my account disabled but error persist. Fix is needed quickly as time running out.
